In [1]:
import pandas as pd

In [3]:
df = pd.read_json("emp.json")

In [4]:
df

   emp_id     name       dept  salary         doj
0     101    Alice         HR   50000  2018-01-15
1     102      Bob         IT   60000  2019-03-10
2     103  Charlie    Finance   55000  2020-07-22
3     104    David         HR   52000  2017-06-30
4     105      Eva         IT   62000  2018-11-05
5     106    Frank    Finance   58000  2019-01-19
6     107    Grace  Marketing   53000  2021-04-23
7     108    Henry         IT   61000  2022-02-14
8     109   Isabel         HR   50000  2020-12-11
9     110     Jack  Marketing   54000  2016-09-27

In [62]:
dict1 = {"empid":[1,2,3],"deptno":[10,20,30]}

In [73]:
dict2 = {"empid":[1,6,7,8,9],"deptno":[10,20,30,40,50]}

In [74]:
df1 = pd.DataFrame(dict1)
df2 = pd.DataFrame(dict2)

In [17]:
df2

   empid  deptno
0      1      10
1      4      20
2      5      30

In [26]:
df_ans = pd.concat([df1,df2],axis=0)

In [27]:
df_ans

   empid  deptno      sal
0      1    10.0      NaN
1      2    20.0      NaN
2      3    30.0      NaN
0      1     NaN  10000.0
1      4     NaN  20000.0
2      5     NaN  30000.0

In [30]:
df_ans = pd.concat([df1,df2],axis=1,join='outer')

In [31]:
df_ans

   empid  deptno  empid    sal
0      1      10      1  10000
1      2      20      4  20000
2      3      30      5  30000

In [32]:
# default join = outer ( similar to union on the indexes)
df_ans = pd.concat([df1,df2],axis=0,join='outer')

In [33]:
df_ans

   empid  deptno      sal
0      1    10.0      NaN
1      2    20.0      NaN
2      3    30.0      NaN
0      1     NaN  10000.0
1      4     NaN  20000.0
2      5     NaN  30000.0

In [85]:
# join = inner ( similar to intersection on the indexes)
df_ans = pd.concat([df1,df2],axis=1,join='inner')

In [86]:
df_ans

   empid  deptno  empid  deptno
0      1      10      1      10
1      2      20      6      20
2      3      30      7      30

In [89]:
# database connectivity
# mysql connection and read the data from table

# pd.read_sql("query","dbconenction")
from sqlalchemy import create_engine
import pandas as pd
mysql_connection = create_engine("mysql+pymysql://root:Admin%40143@localhost:3308/junbatchdb")
sql_query = """select * from emp"""
df = pd.read_sql(sql_query,mysql_connection)

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)